paths:
  BaseAfatarPath: "static/avatars/defaultAvatar.png"
  StaticPathForComments: "static/comments/"
  StaticPathForAvatars: "static/avatars/"
  StaticPathForHotels: "static/img/"
  CertPath: "/etc/ssl/hostelscan/hostelscan.ru.crt"
  KeyPath: "/etc/ssl/hostelscan/hostelscan.ru.key"
cookie:
  LifeTime: 44640
s3:
  S3Url: "https://hostelscan.hb.bizmrg.com/"
  S3Region: "ru-msk"
  S3EndPoint: "https://hb.bizmrg.com"
  BucketName: "hostelscan"
grpc:
  SessionGrpcServicePort: ":8079"
  UserGrpcServicePort: ":8081"
http:
  MainHttpServicePort: ":8080"
constants:
  BasePageCount: 30
  PreviewItemLimit: 6
  BaseItemPerPage: 28
  WishListIn: "WishListIn"
  WishListOut: "WishListOut"
  RecommendationCount: 4
  UpdateRecommendationTick: 5
  PongWait: 5
  MaxMessageSize: 1024
  chatID: -444219540
