// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package chat_mock is a generated GoMock package.
package chat_mock

import (
	chat_model "github.com/go-park-mail-ru/2020_2_JMickhs/main/internal/app/chat/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddMessageInChat mocks base method
func (m *MockRepository) AddMessageInChat(chatID string, message chat_model.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessageInChat", chatID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessageInChat indicates an expected call of AddMessageInChat
func (mr *MockRepositoryMockRecorder) AddMessageInChat(chatID, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageInChat", reflect.TypeOf((*MockRepository)(nil).AddMessageInChat), chatID, message)
}

// AddOrGetChat mocks base method
func (m *MockRepository) AddOrGetChat(chatID string, userID int) ([]chat_model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrGetChat", chatID, userID)
	ret0, _ := ret[0].([]chat_model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrGetChat indicates an expected call of AddOrGetChat
func (mr *MockRepositoryMockRecorder) AddOrGetChat(chatID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrGetChat", reflect.TypeOf((*MockRepository)(nil).AddOrGetChat), chatID, userID)
}

// GetChatID mocks base method
func (m *MockRepository) GetChatID(userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatID", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatID indicates an expected call of GetChatID
func (mr *MockRepositoryMockRecorder) GetChatID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatID", reflect.TypeOf((*MockRepository)(nil).GetChatID), userID)
}

// GetChatHistoryByID mocks base method
func (m *MockRepository) GetChatHistoryByID(chatID string) ([]chat_model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatHistoryByID", chatID)
	ret0, _ := ret[0].([]chat_model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatHistoryByID indicates an expected call of GetChatHistoryByID
func (mr *MockRepositoryMockRecorder) GetChatHistoryByID(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatHistoryByID", reflect.TypeOf((*MockRepository)(nil).GetChatHistoryByID), chatID)
}
