basePath: /
consumes:
- application/json
- multipart/form-data
definitions:
  AddCommentRequest:
    properties:
      hotel_id:
        format: int64
        type: integer
        x-go-name: HotelID
      message:
        type: string
        x-go-name: Message
      rating:
        format: int64
        type: integer
        x-go-name: Rating
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/docs/swagger
  Avatar:
    properties:
      avatar:
        type: string
        x-go-name: Avatar
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/docs/swagger
  Comment:
    description: easyjson:json
    properties:
      comm_id:
        format: int64
        type: integer
        x-go-name: CommID
      hotel_id:
        format: int64
        type: integer
        x-go-name: HotelID
      message:
        type: string
        x-go-name: Message
      rating:
        format: double
        type: number
        x-go-name: Rate
      time:
        type: string
        x-go-name: Time
      user_id:
        format: int64
        type: integer
        x-go-name: UserID
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/internal/app/comment/models
  File:
    allOf:
    - properties:
        Close:
          type: string
      type: object
    - type: object
    - type: object
    - type: object
    description: |-
      Its contents may be either stored in memory or on disk.
      If stored on disk, the File's underlying concrete type will be an *os.File.
    title: File is an interface to access the file part of a multipart message.
    type: object
    x-go-package: mime/multipart
  FullCommentInfo:
    description: easyjson:json
    properties:
      avatar:
        type: string
        x-go-name: Avatar
      comm_id:
        format: int64
        type: integer
        x-go-name: CommID
      hotel_id:
        format: int64
        type: integer
        x-go-name: HotelID
      message:
        type: string
        x-go-name: Message
      rating:
        format: double
        type: number
        x-go-name: Rating
      time:
        type: string
        x-go-name: Time
      user_id:
        format: int64
        type: integer
        x-go-name: UserID
      username:
        type: string
        x-go-name: Username
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/internal/app/comment/models
  GetCommentsRequest:
    properties:
      comments:
        items:
          $ref: '#/definitions/FullCommentInfo'
        type: array
        x-go-name: Comments
      pag_info:
        $ref: '#/definitions/PaginationInfo'
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/docs/swagger
  Hotel:
    description: easyjson:json
    properties:
      comm_count:
        format: int64
        type: integer
        x-go-name: CommCount
      description:
        type: string
        x-go-name: Description
      hotel_id:
        format: int64
        type: integer
        x-go-name: HotelID
      image:
        type: string
        x-go-name: Image
      location:
        type: string
        x-go-name: Location
      name:
        type: string
        x-go-name: Name
      photos:
        items:
          type: string
        type: array
        x-go-name: Photos
      rating:
        format: double
        type: number
        x-go-name: Rating
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/internal/app/hotels/models
  HotelData:
    properties:
      comment:
        $ref: '#/definitions/FullCommentInfo'
      hotel:
        $ref: '#/definitions/Hotel'
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/docs/swagger
  HotelPreview:
    description: easyjson:json
    properties:
      hotel_id:
        format: int64
        type: integer
        x-go-name: HotelID
      image:
        type: string
        x-go-name: Image
      location:
        type: string
        x-go-name: Location
      name:
        type: string
        x-go-name: Name
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/internal/app/hotels/models
  Hotels:
    description: easyjson:json
    properties:
      hotels:
        items:
          $ref: '#/definitions/Hotel'
        type: array
        x-go-name: Hotels
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/internal/app/hotels/models
  HotelsPreview:
    description: easyjson:json
    properties:
      hotels_preview:
        items:
          $ref: '#/definitions/HotelPreview'
        type: array
        x-go-name: Hotels
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/internal/app/hotels/models
  NewRate:
    description: easyjson:json
    properties:
      comment:
        $ref: '#/definitions/Comment'
      new_rate:
        format: double
        type: number
        x-go-name: Rate
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/internal/app/comment/models
  PaginationInfo:
    description: easyjson:json
    properties:
      has_next:
        type: boolean
        x-go-name: HasNext
      has_prev:
        type: boolean
        x-go-name: HasPrev
      num_pages:
        format: int64
        type: integer
        x-go-name: NumPages
      page_num:
        format: int64
        type: integer
        x-go-name: PageNum
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/internal/app/paginator/model
  SafeUser:
    description: easyjson:json
    properties:
      avatar:
        type: string
        x-go-name: Avatar
      email:
        type: string
        x-go-name: Email
      id:
        format: int64
        type: integer
        x-go-name: ID
      username:
        type: string
        x-go-name: Username
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/internal/app/user/models
  SearchDataResponse:
    properties:
      Pag_info:
        $ref: '#/definitions/PaginationInfo'
      hotels:
        items:
          $ref: '#/definitions/Hotel'
        type: array
        x-go-name: Hotels
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/docs/swagger
  UpdateAvatar:
    properties:
      avatar:
        $ref: '#/definitions/File'
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/docs/swagger
  UpdateCommentRequest:
    properties:
      comm_id:
        format: int64
        type: integer
        x-go-name: CommID
      message:
        type: string
        x-go-name: Message
      rating:
        format: int64
        type: integer
        x-go-name: Rate
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/docs/swagger
  UpdatePassword:
    description: easyjson:json
    properties:
      newpassword:
        type: string
        x-go-name: NewPassword
      oldpassword:
        type: string
        x-go-name: OldPassword
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/internal/app/user/models
  UpdateUser:
    properties:
      email:
        type: string
        x-go-name: Email
      username:
        type: string
        x-go-name: Username
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/docs/swagger
  UserAuth:
    properties:
      password:
        type: string
        x-go-name: Password
      username:
        type: string
        x-go-name: Username
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/docs/swagger
  UserRegistation:
    properties:
      email:
        type: string
        x-go-name: Email
      password:
        type: string
        x-go-name: Password
      username:
        type: string
        x-go-name: Username
    type: object
    x-go-package: github.com/go-park-mail-ru/2020_2_JMickhs/docs/swagger
info:
  description: Swagger spec.
  title: Golang service API for HotelScanner
  version: 1.0.0
paths:
  /api/v1/comments:
    get:
      description: GetList of comments
      operationId: comments
      parameters:
      - description: page num start from 0
        format: int64
        in: query
        name: page
        required: true
        type: integer
        x-go-name: Page
      - description: the ID of hotel which comments you get
        format: int64
        in: query
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/comments'
        "400":
          $ref: '#/responses/badrequest'
      tags:
      - comment
    post:
      description: add comment and rate hotel
      operationId: AddComment
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/AddCommentRequest'
      responses:
        "200":
          $ref: '#/responses/AddComment'
        "400":
          $ref: '#/responses/badrequest'
        "403":
          $ref: '#/responses/Forbidden'
        "423":
          $ref: '#/responses/locked'
      tags:
      - comment
    put:
      operationId: UpdateComment
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/UpdateCommentRequest'
      responses:
        "200":
          $ref: '#/responses/AddComment'
        "400":
          $ref: '#/responses/badrequest'
        "403":
          $ref: '#/responses/Forbidden'
        "423":
          $ref: '#/responses/locked'
      tags:
      - comment
  /api/v1/comments/{id}:
    delete:
      operationId: DeleteComment
      parameters:
      - description: the ID to delete comment
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "400":
          $ref: '#/responses/badrequest'
        "403":
          $ref: '#/responses/Forbidden'
      tags:
      - comment
  /api/v1/hotels:
    get:
      description: GetList of hotels
      operationId: hotels
      parameters:
      - description: the start ID to get hotels
        format: int64
        in: query
        name: from
        required: true
        type: integer
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/hotels'
        "400":
          $ref: '#/responses/badrequest'
      tags:
      - hotel
  /api/v1/hotels/{id}:
    get:
      description: if don't rate by curr user, field "rate" should be empty
      operationId: hotel
      parameters:
      - description: the id of hotel to get from database
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/HotelData'
        "400":
          $ref: '#/responses/badrequest'
        "410":
          $ref: '#/responses/gone'
      summary: Get Single hotel by id,
      tags:
      - hotel
  /api/v1/hotels/previewSearch:
    get:
      description: Search hotels preview
      operationId: hotelPreview
      parameters:
      - description: page num start from 0
        in: query
        name: pattern
        required: true
        type: string
        x-go-name: Pattern
      responses:
        "200":
          $ref: '#/responses/hotelsPreview'
        "400":
          $ref: '#/responses/badrequest'
      tags:
      - hotel
  /api/v1/hotels/search:
    get:
      description: Search hotels
      operationId: searchHotel
      parameters:
      - description: page num start from 0
        in: query
        name: pattern
        required: true
        type: string
        x-go-name: Pattern
      - in: query
        name: page
        required: true
        type: string
        x-go-name: Page
      responses:
        "200":
          $ref: '#/responses/searchHotel'
        "400":
          $ref: '#/responses/badrequest'
      tags:
      - hotel
  /api/v1/users:
    get:
      description: Get current safe user
      operationId: user
      responses:
        "200":
          $ref: '#/responses/safeUser'
        "401":
          $ref: '#/responses/unauthorizied'
      tags:
      - Users
    post:
      description: Creates a new User
      operationId: signup
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/UserRegistation'
      responses:
        "200":
          $ref: '#/responses/safeUser'
        "400":
          $ref: '#/responses/badrequest'
        "409":
          $ref: '#/responses/conflict'
      tags:
      - Users
  /api/v1/users/{id}:
    get:
      description: Get info abous user by his id
      operationId: userById
      parameters:
      - format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/safeUser'
        "400":
          $ref: '#/responses/badrequest'
        "410":
          $ref: '#/responses/gone'
      tags:
      - Users
  /api/v1/users/avatar:
    put:
      description: Update Avatar
      operationId: avatar
      parameters:
      - description: avatar in *.jpg *.jpeg *.png format
        in: body
        name: Body
        schema:
          $ref: '#/definitions/UpdateAvatar'
      responses:
        "200":
          $ref: '#/responses/avatar'
        "400":
          $ref: '#/responses/badrequest'
        "401":
          $ref: '#/responses/unauthorizied'
        "403":
          $ref: '#/responses/Forbidden'
        "415":
          $ref: '#/responses/unsupport'
      tags:
      - Users
  /api/v1/users/credentials:
    put:
      description: Get data from form  which need to change and change user data
      operationId: credentials
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/UpdateUser'
      responses:
        "400":
          $ref: '#/responses/badrequest'
        "401":
          $ref: '#/responses/unauthorizied'
        "403":
          $ref: '#/responses/Forbidden'
        "409":
          $ref: '#/responses/conflict'
      tags:
      - Users
  /api/v1/users/password:
    put:
      description: update password
      operationId: password
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/UpdatePassword'
      responses:
        "400":
          $ref: '#/responses/badrequest'
        "401":
          $ref: '#/responses/unauthorizied'
        "402":
          $ref: '#/responses/badCredentials'
        "403":
          $ref: '#/responses/Forbidden'
      tags:
      - Users
  /api/v1/users/sessions:
    delete:
      description: sign out current user and delete cookie session
      operationId: DelSessions
      tags:
      - Sessions
    post:
      description: user auth with coockie
      operationId: AddSessions
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/UserAuth'
      responses:
        "200":
          $ref: '#/responses/safeUser'
        "400":
          $ref: '#/responses/badrequest'
        "401":
          $ref: '#/responses/unauthorizied'
      tags:
      - Sessions
produces:
- application/json
responses:
  AddComment:
    schema:
      $ref: '#/definitions/NewRate'
  Forbidden:
    description: wrong csrf token
  HotelData:
    schema:
      $ref: '#/definitions/HotelData'
  UpdateComment:
    schema:
      $ref: '#/definitions/NewRate'
  avatar:
    schema:
      $ref: '#/definitions/Avatar'
  badCredentials:
    description: wrong credentials
  badrequest:
    description: cannot parse data or undefined query or path parameters
  commentInfo:
    description: easyjson:json
    headers:
      avatar:
        type: string
      comm_id:
        format: int64
        type: integer
      hotel_id:
        format: int64
        type: integer
      message:
        type: string
      rating:
        format: double
        type: number
      time:
        type: string
      user_id:
        format: int64
        type: integer
      username:
        type: string
  comments:
    schema:
      $ref: '#/definitions/GetCommentsRequest'
  conflict:
    description: unique data already exists
  gone:
    description: This data does not exist
  hotels:
    schema:
      $ref: '#/definitions/Hotels'
  hotelsPreview:
    schema:
      $ref: '#/definitions/HotelsPreview'
  locked:
    description: two times rate one hotel
  safeUser:
    schema:
      $ref: '#/definitions/SafeUser'
  searchHotel:
    schema:
      $ref: '#/definitions/SearchDataResponse'
  signup:
    schema:
      $ref: '#/definitions/SafeUser'
  unauthorizied:
    description: user unauthorizied
  unsupport:
    description: Unsupported Media Type
  user:
    description: easyjson:json
    headers:
      avatar:
        type: string
      email:
        type: string
      id:
        format: int64
        type: integer
      password:
        type: string
      username:
        type: string
schemes:
- http
swagger: "2.0"
