{
 "title": "service info",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Hits rate per status ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(hits[$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "hits per method",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(hits[$__interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Hits rate per status ,path and method",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hits", "legendFormat": "{{status}} {{path}} {{method}}" }
   ]
  },
  {
   "title": "avg timings per status",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (status) (irate(timings_bucket[$__interval])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "timings",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,timings_bucket)",
     "legendFormat": "{{status}}{{path}}{{method}}"
    }
   ]
  }
 ]
}