// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package paginationModel

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson47583779DecodeGithubComGoParkMailRu20202JMickhsMainInternalAppPaginatorModel(in *jlexer.Lexer, out *PaginationInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "next":
			out.NextLink = string(in.String())
		case "prev":
			out.PrevLink = string(in.String())
		case "items_count":
			out.ItemsCount = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson47583779EncodeGithubComGoParkMailRu20202JMickhsMainInternalAppPaginatorModel(out *jwriter.Writer, in PaginationInfo) {
	out.RawByte('{')
	first := true
	_ = first
	if in.NextLink != "" {
		const prefix string = ",\"next\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.NextLink))
	}
	if in.PrevLink != "" {
		const prefix string = ",\"prev\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.PrevLink))
	}
	if in.ItemsCount != 0 {
		const prefix string = ",\"items_count\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ItemsCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PaginationInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson47583779EncodeGithubComGoParkMailRu20202JMickhsMainInternalAppPaginatorModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PaginationInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson47583779EncodeGithubComGoParkMailRu20202JMickhsMainInternalAppPaginatorModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PaginationInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson47583779DecodeGithubComGoParkMailRu20202JMickhsMainInternalAppPaginatorModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PaginationInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson47583779DecodeGithubComGoParkMailRu20202JMickhsMainInternalAppPaginatorModel(l, v)
}
