paths:
  BaseAvatarPath: "static/avatars/defaultAvatar.png"
  StaticPathForAvatars: "static/avatars/"
  CertPath: "/etc/ssl/hostelscan/hostelscan.ru.crt"
  KeyPath: "/etc/ssl/hostelscan/hostelscan.ru.key"
cookie:
  LifeTime: 44640
s3:
  S3Url: "https://hostelscan.hb.bizmrg.com/"
  S3Region: "ru-msk"
  S3EndPoint: "https://hb.bizmrg.com"
  BucketName: "hostelscan"
grpc:
  SessionGrpcServicePort: ":8079"
  UserGrpcServicePort: ":8081"
http:
  UserHttpServicePort: ":8082"



