name: Docker Build

on:
  push:
    branches:
      - master
      - dev
      - tests
  pull_request:
    branches:
      - master
      - dev
      - tests

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: servicesTest
        run: make tests
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/golang/lint/golint
          make linter
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker image
        run: sudo docker build -t kostikan/main_service:${GITHUB_SHA::8} -f ./main/Dockerfile . &&
          sudo docker build -t kostikan/session_service:${GITHUB_SHA::8} -f ./sessions/Dockerfile . &&
          sudo docker build -t kostikan/user_service:${GITHUB_SHA::8} -f ./user/Dockerfile .

      - name: Push the image
        run: sudo docker push kostikan/main_service:${GITHUB_SHA::8} &&
          sudo docker push kostikan/session_service:${GITHUB_SHA::8} &&
          sudo docker push kostikan/user_service:${GITHUB_SHA::8}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pull project
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SECRET_KEY   }}
          script: cd backend/ && sudo docker pull kostikan/main_service:${GITHUB_SHA::8} &&
            sudo docker pull kostikan/session_service:${GITHUB_SHA::8} &&
            sudo docker pull kostikan/user_service:${GITHUB_SHA::8}
      - name: run project
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SECRET_KEY }}
          script: docker rm -vf $(docker ps -a -q) || true && cd backend/ &&
            APP_VERSION=${GITHUB_SHA::8} docker-compose up -d --build --no-deps


